{
 "title": "Node.js and Express Metrics",
 "description": "Metrics for node.js and express router status",
 "tags": [
  "node.js",
  "express",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nodejs_version_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, le)"
    }
   },
   {
    "name": "tolerated",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, le)"
    }
   },
   { "name": "restarts_interval", "query": "1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Apdex Score: target $target s, tolerated $tolerated s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n        (   \n                sum(http_request_duration_seconds_bucket{pod=~\"$pod\",le=\"$target\",status_code=~\"2..\"})\n                + (\n                        sum(http_request_duration_seconds_bucket{pod=~\"$pod\",le=\"$tolerated\",status_code=~\"2..\"})\n                        - sum(http_request_duration_seconds_bucket{pod=~\"$pod\",le=\"$target\",status_code=~\"2..\"})\n                ) / 2\n        ) / sum(http_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"2..\"})\n) * 100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\tsum(\n\t\thttp_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"[45]..\"} OR on() vector(0)\n\t) / \n\tsum(\n\t\thttp_request_duration_seconds_count{pod=~\"$pod\"}\n\t)\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_response_length_bytes_sum{pod=~\"$pod\"}) + sum(http_request_length_bytes_sum{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_response_length_bytes_sum{pod=~\"$pod\"}[$interval])) + sum(rate(http_request_length_bytes_sum{pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Restarts in $restarts_interval",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{pod=~\"$pod\"}[$restarts_interval]))"
    }
   ]
  },
  {
   "title": "Node.js Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of CPU Time Spent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "virtual memory"
    },
    {
     "expr": "process_heap_bytes{pod=~\"$pod\"}",
     "legendFormat": "heap memory"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{pod=~\"$pod\"}",
     "legendFormat": "last"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{pod=~\"$pod\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{pod=~\"$pod\"}",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{pod=~\"$pod\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{pod=~\"$pod\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Node.js Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{pod=~\"$pod\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{pod=~\"$pod\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{pod=~\"$pod\"}",
     "legendFormat": "total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{pod=~\"$pod\"}",
     "legendFormat": "used"
    },
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "nodejs_external_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Express Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Apdex Score: target $target s, tolerated $tolerated s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n        (   \n                sum(http_request_duration_seconds_bucket{pod=~\"$pod\",le=\"$target\",status_code=~\"2..\"})\n                + (\n                        sum(http_request_duration_seconds_bucket{pod=~\"$pod\",le=\"$tolerated\",status_code=~\"2..\"})\n                        - sum(http_request_duration_seconds_bucket{pod=~\"$pod\",le=\"$target\",status_code=~\"2..\"})\n                ) / 2\n        ) / sum(http_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"2..\"})\n) * 100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "Requests Per Seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\"}[$interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request per Seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\"}[$interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Count by Status Code",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{pod=~\"$pod\"}) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$interval])) by (status_code,le))",
     "legendFormat": "{{status_code}} (95%)"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$interval])) by (status_code,le))",
     "legendFormat": "{{status_code}} (100%)"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_length_bytes_sum{pod=~\"$pod\"}) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Duration",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "topk(5, sum by (path)(rate(http_request_duration_seconds_sum{pod=~\"$pod\"}[$interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Duration",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 46 },
   "targets": [
    {
     "expr": "topk(5, sum by (path)(rate(http_request_duration_seconds_sum{pod=~\"$pod\",status_code=~\"[23]..\"}[$interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Duration",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "topk(5, sum by (path)(rate(http_request_duration_seconds_sum{pod=~\"$pod\",status_code=~\"[45]..\"}[$interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Count",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "topk(5, sum by (path)(increase(http_request_duration_seconds_count{pod=~\"$pod\"}[$interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Count",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 46 },
   "targets": [
    {
     "expr": "topk(5, increase(http_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"[23]..\"}[$interval]))",
     "legendFormat": "{{status_code}}  {{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Count",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 46 },
   "targets": [
    {
     "expr": "topk(5, increase(http_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"[45]..\"}[$interval]))",
     "legendFormat": "{{status_code}}  {{path}}"
    }
   ]
  }
 ]
}